name: student_shopping_v1
description: Student shopping

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  overlay_support:
  shared_preferences: ^2.0.13
  carousel_slider: ^4.1.1
#  firebase_core: ^1.4.0
  firebase_core: ^1.17.0
#  cloud_firestore: ^3.1.10
  socket_io_client: ^2.0.0
  pinput: ^2.2.16
  heic_to_jpg: ^0.2.0
  flutter_search_bar: ^3.0.0-dev.1
  url_launcher: ^6.1.6
#  firebase_auth: ^3.0.1
  firebase_auth: ^3.3.4
  email_validator: ^2.0.1
  google_sign_in: ^5.1.0
  flutter_signin_button: ^2.0.0
  http: ^0.13.3
  simple_animations: ^4.0.0
  json_annotation: ^4.6.0
  firebase_auth_platform_interface: ^6.0.0
  firebase_auth_web: ^3.0.0
  firebase_core_platform_interface: ^4.0.1
  firebase_admin: ^0.2.0
  infinite_scroll_pagination: 3.0.0
#  infinite_scroll_pagination: ^3.1.0
  flutter_spinkit: ^5.1.0
  another_carousel_pro:
    git:
      url: https://github.com/iamnabink/another_carousel_pro.git
      ref: master
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  sliver_tools: ^0.2.5
  intl: ^0.17.0
  firebase_messaging: ^12.0.1
  flutter_local_notifications: ^9.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.0.1
#  firebase_storage:
#  firebase_storage_web:
  fluttertoast: ^8.0.3
  cached_network_image: ^3.0.0
#  image_picker: ^0.8.4+1
  image_picker: ^0.8.5+3
  permission_handler: ^8.1.6
  build_runner: ^2.0.5
  #  json_serializable: ^5.0.2
  json_serializable: any
  file_picker: ^4.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages