// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKGwXpFnl2dpeE4sXtGd11gdVGchsk7eQ',
    appId: '1:1039454868573:android:0fbf3f06f95d5eacf9a9b4',
    messagingSenderId: '1039454868573',
    projectId: 'student-shopping',
    storageBucket: 'student-shopping.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1_l754lsEAbXxD0-JKUqFmhhWlnfw-p4',
    appId: '1:1039454868573:ios:fb78190e0bf980aaf9a9b4',
    messagingSenderId: '1039454868573',
    projectId: 'student-shopping',
    storageBucket: 'student-shopping.appspot.com',
    androidClientId: '1039454868573-f5a0k92gvqmcl418t13b7qbj6gihrnf2.apps.googleusercontent.com',
    iosClientId: '1039454868573-vcbrdkcuihheh864r8o2cq41khkjen8g.apps.googleusercontent.com',
    iosBundleId: 'com.glosoft.studentshopping',
  );
}
